microstrain_inertial_driver:
  ros__parameters:
    # Copy this file to a new file, fill out this section with desired parameters, and specify the new file via params_file to override the default params
    port: /dev/ttyACM1
    imu_frame_id: "base_link"
    imu_data_rate: 200
    use_ros_time: true
